spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_schema
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database: mysql
    open-in-view: false
  application:
    name: 'Sweater App'
  mustache:
    expose-request-attributes: true
